### ISSUE TITLE
Issues with generated  Python func.py

### ISSUE THREAD

**Issue by michael-w-williams** [fnproject/fdk-python#36]
When I tested the Python tutorial I ran into a couple of issues. 

## Fn Run

When I called `fn run` I get the following output:

```
Building image fndemouser/pythonfn:0.0.1 ...............................................................................
starting the request parsing
Before JSON parsing: b'{"call_id":"12345678901234567890123456","content_type":"application/json","deadline":"2018-03-27T17:33:18-06:00","body":"","protocol":{"type":"http","method":"GET","request_url":"http://localhost:8080/myapp/hello","headers":{"Content-Type":["application/json"]}}}\n'
entering handle_request
request parsed
context allocated
starting the function

the function finished
Prepared response: {"body":"\"Hello World\"","content_type":"text\/plain","protocol":{"status_code":200,"headers":{"content-length":["13"]}}}
starting the request parsing
Before JSON parsing: b'\n'
"Hello World"Traceback (most recent call last):
  File "func.py", line 12, in <module>
    fdk.handle(handler)
  File "/usr/local/lib/python3.6/site-packages/fdk/__init__.py", line 29, in handle
    handle_func, runner.read_json(stdin)))
  File "/usr/local/lib/python3.6/site-packages/fdk/runner.py", line 120, in read_json
    return ujson.loads(line)
ValueError: Expected object or value
ERROR: exit status 1
```

The "Hello World" is returned but not in a JSON format.
Plus all that extra information.

If you run

>```sh
> $ echo -n '{"name":"bob"}' | fn run
>```

then the results are:

```
Building image fndemouser/pythonfn:0.0.1 
starting the request parsing
Before JSON parsing: b'{"call_id":"12345678901234567890123456","content_type":"application/json","deadline":"2018-03-27T17:37:25-06:00","body":"{\\"name\\":\\"bob\\"}","protocol":{"type":"http","method":"POST","request_url":"http://localhost:8080/myapp/hello","headers":{"Content-Type":["application/json"]}}}\n'
entering handle_request
request parsed
context allocated
starting the function
{"name":"bob"}
the function finished
Prepared response: {"body":"\"Hello bob\"","content_type":"text\/plain","protocol":{"status_code":200,"headers":{"content-length":["11"]}}}
starting the request parsing
Before JSON parsing: b'\n'
"Hello bob"Traceback (most recent call last):
  File "func.py", line 12, in <module>
    fdk.handle(handler)
  File "/usr/local/lib/python3.6/site-packages/fdk/__init__.py", line 29, in handle
    handle_func, runner.read_json(stdin)))
  File "/usr/local/lib/python3.6/site-packages/fdk/runner.py", line 120, in read_json
    return ujson.loads(line)
ValueError: Expected object or value
ERROR: exit status 1
```

The value "Hello bob" is returned again with a lot of extra information.

## fn call and curl

With `fn call ` and `curl` the correct values are returned, just not in a JSON format.

* `"Hello World"`
* `"Hello Bob"`

**Comment by denismakogon** [comment]
First of all, it’s not clear to me what “not in JSON format” statement means. Autogenerated code from the CLI returns a string not the JSON object.

All that extra information you’ve mentioned is a function logs that are going to the STDERR.

Unfortunately, with current CLI implementation I can’t make `fn run` and `fn test` call result stable. But `fn call` works well, as expected.

**Comment by riconnon** [comment]
Part of the problem here seems to be that the python FDK expects the function to return "something that is JSON serialisable" where the Go FDK expects the function to return a JSON encoded message.

I think that the FDKs should probably be consistent about where data is (de)serialised.

The Python FDK seems strange in that it passes a JSON string in as `data` but expects a native object back as a return value.

**Comment by denismakogon** [comment]
That’s not true. FDK returns whatever your function will return, no matter if that is a JSON object or not.

FDK-python has weird request read algorithm because there are no non-blocking IO mechanisms to read from stream (note that all `.read` is blocking, once and forever).

This particular issue will be resolved as soon as we’d use agent’s code to process protocol IO we have at Fn.

**Comment by denismakogon** [comment]
> The Python FDK seems strange in that it passes a JSON string in as data but expects a native object back as a return value.

That’s not true, actually. You can return whatever that can be deserialized into a json.

**Comment by denismakogon** [comment]
> I think that the FDKs should probably be consistent about where data is (de)serialised.

That’s not actually possible due to certain lang limitations like streams they work different in Go and Python, Ruby, Node. We tried to design FDKs similar to AWS Lambdas FDK.
